### ISSUE TITLE
Automated Text/Email Reminders for Events

### ISSUE THREAD

**Issue by krivero** [Robert-Garcia552/United-Way-Project#12]
### User Story
As a user,
when I register for an event
I would like to receive automated text/emails as a reminder for that event
so that I can keep organized.

### Acceptance Criteria
- receive email or text as soon as register
- receive monthly
- a week in advance

**Comment by Robert-Garcia552** [comment]
Get a monthly email reminding to sign up for events. Newsletter type.

Reminders for rsvps.
